// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"RestAPI/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryInterface creates a new instance of MockRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type MockRepositoryInterface struct {
	mock.Mock
}

type MockRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryInterface) EXPECT() *MockRepositoryInterface_Expecter {
	return &MockRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) CreateItem(ctx context.Context, item *domain.Item) (*domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Item) (*domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Item) *domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockRepositoryInterface_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *Item
func (_e *MockRepositoryInterface_Expecter) CreateItem(ctx any, item any) *MockRepositoryInterface_CreateItem_Call {
	return &MockRepositoryInterface_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockRepositoryInterface_CreateItem_Call) Run(run func(ctx context.Context, item *domain.Item)) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Item
		if args[1] != nil {
			arg1 = args[1].(*domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_CreateItem_Call) Return(item1 *domain.Item, err error) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockRepositoryInterface_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item *domain.Item) (*domain.Item, error)) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) GetItemByID(ctx context.Context, id int64) (*domain.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepositoryInterface_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepositoryInterface_Expecter) GetItemByID(ctx any, id any) *MockRepositoryInterface_GetItemByID_Call {
	return &MockRepositoryInterface_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockRepositoryInterface_GetItemByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_GetItemByID_Call) Return(item *domain.Item, err error) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockRepositoryInterface_GetItemByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Item, error)) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}
