// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"RestAPI/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryInterface creates a new instance of MockRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type MockRepositoryInterface struct {
	mock.Mock
}

type MockRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryInterface) EXPECT() *MockRepositoryInterface_Expecter {
	return &MockRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) Close() {
	_mock.Called()
	return
}

// MockRepositoryInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepositoryInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepositoryInterface_Expecter) Close() *MockRepositoryInterface_Close_Call {
	return &MockRepositoryInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRepositoryInterface_Close_Call) Run(run func()) *MockRepositoryInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryInterface_Close_Call) Return() *MockRepositoryInterface_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepositoryInterface_Close_Call) RunAndReturn(run func()) *MockRepositoryInterface_Close_Call {
	_c.Run(run)
	return _c
}

// CreateItem provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) CreateItem(ctx context.Context, item *domain.Item) (*domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Item) (*domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Item) *domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockRepositoryInterface_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *domain.Item
func (_e *MockRepositoryInterface_Expecter) CreateItem(ctx any, item any) *MockRepositoryInterface_CreateItem_Call {
	return &MockRepositoryInterface_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockRepositoryInterface_CreateItem_Call) Run(run func(ctx context.Context, item *domain.Item)) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Item
		if args[1] != nil {
			arg1 = args[1].(*domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_CreateItem_Call) Return(item1 *domain.Item, err error) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockRepositoryInterface_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item *domain.Item) (*domain.Item, error)) *MockRepositoryInterface_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) DeleteItem(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryInterface_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockRepositoryInterface_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepositoryInterface_Expecter) DeleteItem(ctx any, id any) *MockRepositoryInterface_DeleteItem_Call {
	return &MockRepositoryInterface_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *MockRepositoryInterface_DeleteItem_Call) Run(run func(ctx context.Context, id int64)) *MockRepositoryInterface_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_DeleteItem_Call) Return(err error) *MockRepositoryInterface_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryInterface_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepositoryInterface_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) GetAllItems(ctx context.Context, limit int, offset int) ([]*domain.Item, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []*domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Item, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Item); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockRepositoryInterface_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRepositoryInterface_Expecter) GetAllItems(ctx any, limit any, offset any) *MockRepositoryInterface_GetAllItems_Call {
	return &MockRepositoryInterface_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx, limit, offset)}
}

func (_c *MockRepositoryInterface_GetAllItems_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRepositoryInterface_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_GetAllItems_Call) Return(items []*domain.Item, err error) *MockRepositoryInterface_GetAllItems_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockRepositoryInterface_GetAllItems_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.Item, error)) *MockRepositoryInterface_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItemsCount provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) GetAllItemsCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItemsCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_GetAllItemsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItemsCount'
type MockRepositoryInterface_GetAllItemsCount_Call struct {
	*mock.Call
}

// GetAllItemsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryInterface_Expecter) GetAllItemsCount(ctx any) *MockRepositoryInterface_GetAllItemsCount_Call {
	return &MockRepositoryInterface_GetAllItemsCount_Call{Call: _e.mock.On("GetAllItemsCount", ctx)}
}

func (_c *MockRepositoryInterface_GetAllItemsCount_Call) Run(run func(ctx context.Context)) *MockRepositoryInterface_GetAllItemsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_GetAllItemsCount_Call) Return(n int, err error) *MockRepositoryInterface_GetAllItemsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepositoryInterface_GetAllItemsCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockRepositoryInterface_GetAllItemsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) GetItemByID(ctx context.Context, id int64) (*domain.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepositoryInterface_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepositoryInterface_Expecter) GetItemByID(ctx any, id any) *MockRepositoryInterface_GetItemByID_Call {
	return &MockRepositoryInterface_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockRepositoryInterface_GetItemByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_GetItemByID_Call) Return(item *domain.Item, err error) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockRepositoryInterface_GetItemByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Item, error)) *MockRepositoryInterface_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// ItemsCount provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) ItemsCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ItemsCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_ItemsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ItemsCount'
type MockRepositoryInterface_ItemsCount_Call struct {
	*mock.Call
}

// ItemsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryInterface_Expecter) ItemsCount(ctx any) *MockRepositoryInterface_ItemsCount_Call {
	return &MockRepositoryInterface_ItemsCount_Call{Call: _e.mock.On("ItemsCount", ctx)}
}

func (_c *MockRepositoryInterface_ItemsCount_Call) Run(run func(ctx context.Context)) *MockRepositoryInterface_ItemsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_ItemsCount_Call) Return(n int64, err error) *MockRepositoryInterface_ItemsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepositoryInterface_ItemsCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockRepositoryInterface_ItemsCount_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryInterface_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepositoryInterface_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryInterface_Expecter) Ping(ctx any) *MockRepositoryInterface_Ping_Call {
	return &MockRepositoryInterface_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRepositoryInterface_Ping_Call) Run(run func(ctx context.Context)) *MockRepositoryInterface_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_Ping_Call) Return(err error) *MockRepositoryInterface_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryInterface_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepositoryInterface_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockRepositoryInterface
func (_mock *MockRepositoryInterface) UpdateItem(ctx context.Context, item *domain.UpdateItemInput, id int64) (*domain.Item, error) {
	ret := _mock.Called(ctx, item, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UpdateItemInput, int64) (*domain.Item, error)); ok {
		return returnFunc(ctx, item, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UpdateItemInput, int64) *domain.Item); ok {
		r0 = returnFunc(ctx, item, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UpdateItemInput, int64) error); ok {
		r1 = returnFunc(ctx, item, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryInterface_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockRepositoryInterface_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *domain.UpdateItemInput
//   - id int64
func (_e *MockRepositoryInterface_Expecter) UpdateItem(ctx any, item any, id any) *MockRepositoryInterface_UpdateItem_Call {
	return &MockRepositoryInterface_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item, id)}
}

func (_c *MockRepositoryInterface_UpdateItem_Call) Run(run func(ctx context.Context, item *domain.UpdateItemInput, id int64)) *MockRepositoryInterface_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UpdateItemInput
		if args[1] != nil {
			arg1 = args[1].(*domain.UpdateItemInput)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryInterface_UpdateItem_Call) Return(item1 *domain.Item, err error) *MockRepositoryInterface_UpdateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockRepositoryInterface_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *domain.UpdateItemInput, id int64) (*domain.Item, error)) *MockRepositoryInterface_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
